"""initial

Revision ID: f29968306458
Revises: 
Create Date: 2021-12-02 18:29:54.170508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29968306458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEFAULT', 'CUSTOM', 'NEW_LEAD', name='campaignmanagetype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('channel_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('location_link', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('address_detail', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('aingine_source_id', sa.Integer(), nullable=True),
    sa.Column('automatic_engagement', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_optin_consent_method', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_table('eval_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('include', sa.Boolean(), nullable=True),
    sa.Column('exclude', sa.Boolean(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MULTISELECT', 'SELECT', 'TEXT', 'TEMPLATE', 'RANGE', name='filtergrouptype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filter_field', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lead_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_source', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_status_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ACTIVE', 'LOST', 'SOLD', name='leadtype'), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nudge_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('display', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'type')
    )
    op.create_table('vehicle_of_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('trim', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vs_extract_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('extract_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vs_lead_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.String(length=16), nullable=False),
    sa.Column('lead_source_id', sa.Integer(), nullable=True),
    sa.Column('vs_lead_source_id', sa.Integer(), nullable=True),
    sa.Column('vs_lead_source_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vs_lead_source_id')
    )
    op.create_table('company_lead_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('lead_source_original_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['lead_source_original_id'], ['lead_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_nudge_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nudge_event_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('start_delay', sa.Integer(), nullable=False),
    sa.Column('start_delay_type', sa.Enum('MINUTES', 'HOURS', 'DAYS', name='startdelaytype'), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('frequency_type', sa.Enum('MINUTES', 'HOURS', 'DAYS', name='frequencytype'), nullable=False),
    sa.Column('first_template_text', sa.String(), nullable=False),
    sa.Column('reminder_template_text', sa.String(), nullable=False),
    sa.Column('is_sms', sa.Boolean(), nullable=True),
    sa.Column('is_web_push', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['nudge_event_id'], ['nudge_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('week_day', sa.Enum('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='weekday'), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('integration_type', sa.Enum('ADF', 'DS', 'VIN', name='crmintegrationtype'), nullable=False),
    sa.Column('adf_email', sa.String(), nullable=True),
    sa.Column('crm_dealer_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('vs_lead_source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('verb', sa.String(), nullable=True),
    sa.Column('direct_object_id', sa.Integer(), nullable=True),
    sa.Column('indirect_object_id', sa.Integer(), nullable=True),
    sa.Column('prepositional_object_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['direct_object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['indirect_object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['prepositional_object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('can_create_users', sa.Boolean(), nullable=True),
    sa.Column('can_create_teams', sa.Boolean(), nullable=True),
    sa.Column('can_view_prospects', sa.Boolean(), nullable=True),
    sa.Column('is_company_admin', sa.Boolean(), nullable=True),
    sa.Column('can_view_auto_analytics', sa.Boolean(), nullable=True),
    sa.Column('can_view_ad_export', sa.Boolean(), nullable=True),
    sa.Column('can_view_clm', sa.Boolean(), nullable=True),
    sa.Column('can_view_gle', sa.Boolean(), nullable=True),
    sa.Column('can_view_engagements', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selection_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('filter_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filter_type_id'], ['filter_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('cognito_id', sa.String(length=128), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('profile_pic', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVATED', name='userstatus'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('vs_lead_status_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vs_lead_status_id', sa.Integer(), nullable=True),
    sa.Column('vs_lead_status', sa.String(), nullable=True),
    sa.Column('vs_lead_status_type_id', sa.Integer(), nullable=True),
    sa.Column('vs_lead_status_type', sa.String(), nullable=True),
    sa.Column('lead_status_type_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_status_type_id'], ['lead_status_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aingine_data_received',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('aingine_data_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACCEPTED', 'REJECTED', 'SAVED', 'VIEWED', name='ainginedatastatus'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('method', sa.Enum('Text', 'Email', name='campaignmethodtype'), nullable=False),
    sa.Column('text_message', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('campaign_type_id', sa.Integer(), nullable=True),
    sa.Column('active_ind', sa.Enum('Active', 'InPogress', 'Inactive', name='campaignindicatortype'), nullable=False),
    sa.Column('is_accept_terms', sa.Boolean(), nullable=True),
    sa.Column('accept_terms_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('is_prioritize', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_type_id'], ['campaign_types.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('selection_option_id', sa.Integer(), nullable=False),
    sa.Column('user_can_change', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['selection_option_id'], ['selection_option.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_lead_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_pull_processing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lock', sa.Boolean(), nullable=True),
    sa.Column('last_pull_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_successfull_created_utc', sa.DateTime(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['crm_integration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('aingine_data_id', sa.Integer(), nullable=False),
    sa.Column('aingine_user_id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Enum('HOT', 'WARM', 'COLD', name='dealstrength'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEAL_WON', 'DEAL_LOST', 'PUSHED_CRM', 'EXPIRED', 'ARCHIVED', name='dealstatus'), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('followup_date', sa.DateTime(), nullable=True),
    sa.Column('allow_notifications', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('post_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_company_shared', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_time', sa.Time(), nullable=True),
    sa.Column('minimum_count', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('last_exported', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('ad_hoc', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fcm_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IOS', 'ANDROID', 'WEB', name='device_types'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notifications_allowed', sa.Boolean(), nullable=True),
    sa.Column('dnd_start', sa.Time(), nullable=True),
    sa.Column('dnd_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('email', sa.Boolean(), nullable=True),
    sa.Column('app', sa.Boolean(), nullable=True),
    sa.Column('sms', sa.Boolean(), nullable=True),
    sa.Column('responses', sa.Boolean(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_initial_response', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screen_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('aingine_user_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='teamstatus'), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twilio_phone_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GENERAL', 'ACTIVITY_CENTER', 'CAMPAIGN', 'APPOINTMENT', name='phoneusetype'), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVATED', 'DISABLED', name='useraccountstatus'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vin_solutions_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vs_user_id', sa.Integer(), nullable=False),
    sa.Column('crm_integration_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crm_integration_id'], ['crm_integration.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vs_extracted_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vs_extract_history_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.String(length=16), nullable=False),
    sa.Column('vs_lead_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('vs_contact_id', sa.Integer(), nullable=False),
    sa.Column('vs_co_buyer_contact_id', sa.Integer(), nullable=True),
    sa.Column('vs_lead_source_id', sa.Integer(), nullable=True),
    sa.Column('vs_lead_status', sa.String(), nullable=True),
    sa.Column('vs_lead_status_type', sa.String(), nullable=True),
    sa.Column('vs_lead_status_mapping_id', sa.Integer(), nullable=True),
    sa.Column('vs_lead_type', sa.String(), nullable=True),
    sa.Column('vs_lead_category', sa.String(), nullable=True),
    sa.Column('vs_create_date', sa.DateTime(), nullable=True),
    sa.Column('do_not_email', sa.Boolean(), nullable=True),
    sa.Column('do_not_call', sa.Boolean(), nullable=True),
    sa.Column('do_not_mail', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vs_extract_history_id'], ['vs_extract_history.id'], ),
    sa.ForeignKeyConstraint(['vs_lead_status_mapping_id'], ['vs_lead_status_mapping.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vs_contact_id'),
    sa.UniqueConstraint('vs_lead_id')
    )
    op.create_table('campaign_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('ONCE', 'REPEAT', name='scheduletype'), nullable=False),
    sa.Column('numeric_value', sa.Integer(), nullable=True),
    sa.Column('temporal_value', sa.Enum('MINUTES', 'HOURS', 'DAYS', 'WEEKS', 'MONTHS', name='temporaltype'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('DEFAULT', 'SOURCE', 'LEAD', 'FILE', 'STATUS', name='campaigntype'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ORIGINAL', 'SENT', 'RECEIVED', 'NOTE', name='entrytype'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('aingine_user_id', sa.Integer(), nullable=True),
    sa.Column('aingine_data_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('is_temp', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('dealer_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('crm_integration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crm_integration_id'], ['crm_integration.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_config_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['export_config_id'], ['export_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('lead_source_type', sa.Enum('CRM', 'FILE', 'SMAI', 'MANUAL', name='leadsourcetype'), nullable=False),
    sa.Column('lead_source_original_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('lead_file_id', sa.Integer(), nullable=True),
    sa.Column('crm_integration_id', sa.Integer(), nullable=True),
    sa.Column('lead_status_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lead_created_date', sa.DateTime(), nullable=True),
    sa.Column('email_consent', sa.Boolean(), nullable=True),
    sa.Column('email_consent_date', sa.DateTime(), nullable=True),
    sa.Column('text_consent_status', sa.Enum('ACCEPTED', 'PENDING', 'DECLINED', name='textconsentstatus'), nullable=True),
    sa.Column('text_consent', sa.Boolean(), nullable=True),
    sa.Column('text_consent_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('other_source', sa.String(length=50), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=True),
    sa.Column('disable_conversation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['crm_integration_id'], ['crm_integration.id'], ),
    sa.ForeignKeyConstraint(['lead_file_id'], ['company_lead_files.id'], ),
    sa.ForeignKeyConstraint(['lead_source_original_id'], ['lead_source.id'], ),
    sa.ForeignKeyConstraint(['lead_status_type_id'], ['lead_status_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_config_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(), nullable=True),
    sa.Column('filter_set_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('notification_config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filter_set_id'], ['filter_set.id'], ),
    sa.ForeignKeyConstraint(['notification_config_id'], ['notification_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('aingine_user_id', sa.Integer(), nullable=True),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('company_filter_id', sa.Integer(), nullable=True),
    sa.Column('filter_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_filter_id'], ['company_filter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_set_id'], ['filter_set.id'], ),
    sa.ForeignKeyConstraint(['filter_type_id'], ['filter_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('company_filter_id', sa.Integer(), nullable=True),
    sa.Column('set_type', sa.String(), nullable=True),
    sa.Column('export_config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_filter_id'], ['company_filter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['export_config_id'], ['export_config.id'], ),
    sa.ForeignKeyConstraint(['filter_type_id'], ['filter_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vs_sms_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vs_contact_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('phone_type', sa.String(), nullable=True),
    sa.Column('subscriber_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vs_contact_id'], ['vs_extracted_lead.vs_contact_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_lead_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('last_message_sent_date', sa.DateTime(), nullable=True),
    sa.Column('last_message_received_date', sa.DateTime(), nullable=True),
    sa.Column('num_attempts_before_response', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UNCONTACTED', 'QUEUED', 'SENT', 'FAILED', 'DELIVERED', 'RESPONDED', 'ENGAGED', 'OPT_OUT', name='campaignleadstatustype'), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('template_text', sa.String(), nullable=True),
    sa.Column('after_hour_template_text', sa.String(), nullable=True),
    sa.Column('is_after_hour', sa.Boolean(), nullable=True),
    sa.Column('active_ind', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['campaign_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['lead_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('location_text', sa.String(), nullable=True),
    sa.Column('address_line_1', sa.String(), nullable=True),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_conversation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('disable_conversation', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_text', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('phone_type', sa.String(), nullable=True),
    sa.Column('lookup_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('lead_status_type_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['lead_status_type_id'], ['lead_status_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_vehicle_of_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('trim', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('customer_interest', sa.Enum('BUY', 'SELL', 'TRADE', 'NONE', name='customerinteresttype'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('scheduled_seconds', sa.Integer(), nullable=True),
    sa.Column('repeat_scheduled_seconds', sa.Integer(), nullable=True),
    sa.Column('execution_arn', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('lead_email', sa.String(), nullable=True),
    sa.Column('lead_phone', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.Column('appointment_status', sa.Enum('SCHEDULED', 'RESCHEDULED', 'SHOWED', 'CANCELLED', 'NO_SHOWED', name='appointmentstatus'), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('discussed_voi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['discussed_voi_id'], ['lead_vehicle_of_interest.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('lead_email', sa.String(), nullable=True),
    sa.Column('lead_phone', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('appointment_status', sa.Enum('SCHEDULED', 'RESCHEDULED', 'SHOWED', 'CANCELLED', 'NO_SHOWED', name='appointmentstatus'), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('discussed_voi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discussed_voi_id'], ['lead_vehicle_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_user_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('campaign_template_id', sa.Integer(), nullable=True),
    sa.Column('message_sid', sa.String(), nullable=True),
    sa.Column('message_status', sa.String(), nullable=True),
    sa.Column('direction', sa.Enum('TO_LEAD', 'TO_USER', 'FROM_LEAD', 'FROM_USER', name='messagedirection'), nullable=True),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.Column('date_received', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('message_type', sa.Enum('APPOINTMENT', 'REMINDER', 'NORMAL', name='messagetype'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['campaign_template_id'], ['campaign_templates.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['system_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_campaign_id'), 'message', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_message_lead_id'), 'message', ['lead_id'], unique=False)
    op.create_index(op.f('ix_message_message_status'), 'message', ['message_status'], unique=False)
    op.create_index(op.f('ix_message_system_user_id'), 'message', ['system_user_id'], unique=False)
    op.create_index(op.f('ix_message_user_id'), 'message', ['user_id'], unique=False)
    op.create_table('vin_solutions_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vs_vehicle_id', sa.String(), nullable=False),
    sa.Column('lead_vehicle_of_interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_vehicle_of_interest_id'], ['lead_vehicle_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('from_phone', sa.String(), nullable=True),
    sa.Column('to_phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nudge_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_nudge_event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['company_nudge_event_id'], ['company_nudge_event.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_appointment_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('execution_arn', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nudge_activity_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nudge_activity_id', sa.Integer(), nullable=True),
    sa.Column('execution_arn', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('trigger_on', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nudge_activity_id'], ['nudge_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nudge_activity_history')
    op.drop_table('scheduled_appointment_reminder')
    op.drop_table('nudge_activity')
    op.drop_table('message_log')
    op.drop_table('vin_solutions_vehicles')
    op.drop_index(op.f('ix_message_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_system_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_message_status'), table_name='message')
    op.drop_index(op.f('ix_message_lead_id'), table_name='message')
    op.drop_index(op.f('ix_message_campaign_id'), table_name='message')
    op.drop_table('message')
    op.drop_table('appointment_history')
    op.drop_table('appointment')
    op.drop_table('schedule_messages')
    op.drop_table('lead_vehicle_of_interest')
    op.drop_table('lead_status_history')
    op.drop_table('lead_phones')
    op.drop_table('lead_notes')
    op.drop_table('lead_emails')
    op.drop_table('lead_conversation_history')
    op.drop_table('lead_addresses')
    op.drop_table('campaign_templates')
    op.drop_table('campaign_lead_summary')
    op.drop_table('vs_sms_preferences')
    op.drop_table('user_filter')
    op.drop_table('team_member')
    op.drop_table('saved_filter')
    op.drop_table('response_config')
    op.drop_table('notification_config_detail')
    op.drop_table('leads')
    op.drop_table('export')
    op.drop_table('crm_lead')
    op.drop_table('conversation_entry')
    op.drop_table('campaign_selections')
    op.drop_table('campaign_schedules')
    op.drop_table('vs_extracted_lead')
    op.drop_table('vin_solutions_user')
    op.drop_table('user_roles')
    op.drop_table('user_accounts')
    op.drop_table('twilio_phone_service')
    op.drop_table('team')
    op.drop_table('screen_name')
    op.drop_table('response_template')
    op.drop_table('notification_config')
    op.drop_table('notification')
    op.drop_table('filter_set')
    op.drop_table('fcm_device')
    op.drop_table('export_config')
    op.drop_table('engagement_message_template')
    op.drop_table('deal')
    op.drop_table('crm_pull_processing')
    op.drop_table('company_lead_files')
    op.drop_table('company_filter')
    op.drop_table('campaign')
    op.drop_table('aingine_data_received')
    op.drop_table('vs_lead_status_mapping')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('selection_option')
    op.drop_table('role')
    op.drop_table('event')
    op.drop_table('crm_integration')
    op.drop_table('company_working_hours')
    op.drop_table('company_nudge_event')
    op.drop_table('company_lead_source')
    op.drop_table('vs_lead_source')
    op.drop_table('vs_extract_history')
    op.drop_table('vehicle_of_interest')
    op.drop_table('object')
    op.drop_table('nudge_event')
    op.drop_table('lead_status_type')
    op.drop_table('lead_source')
    op.drop_table('filter_type')
    op.drop_table('eval_term')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    op.drop_table('channel')
    op.drop_table('campaign_types')
    # ### end Alembic commands ###
