# Generated by Django 3.2.9 on 2021-11-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=150)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
