# Generated by Django 3.2.9 on 2021-11-12 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211111_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Free', 'free'), ('Premium', 'premium')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('stripe_plan_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.membership')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_sub_id', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('user_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermembership')),
            ],
        ),
    ]
