# Generated by Django 3.2.9 on 2021-11-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211112_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
