# Generated by Django 3.2.9 on 2021-11-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_parent_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
