"""extra user fields

Revision ID: 5a7603976469
Revises: 4d34325be0fa
Create Date: 2021-11-01 17:18:45.813320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7603976469'
down_revision = '4d34325be0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.drop_column('user', 'bout_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bout_me', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
