# Generated by Django 3.2.5 on 2021-11-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='site/logo/')),
                ('qr_code_text', models.TextField()),
                ('project_rate', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Project Rate')),
                ('layer_rate', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Layer Rate')),
                ('duration', models.IntegerField(default=1)),
                ('duration_period', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=100)),
                ('trial_duration', models.IntegerField(default=1)),
                ('trial_duration_period', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=100)),
                ('due_days', models.IntegerField(default=30, verbose_name='Due Days')),
            ],
            options={
                'verbose_name_plural': 'Super Admin Settings',
            },
        ),
    ]
