"""titme field added to banner

Revision ID: 540ef7f351e6
Revises: f6d0dbf9ef56
Create Date: 2021-11-02 17:25:02.144544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540ef7f351e6'
down_revision = 'f6d0dbf9ef56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'title')
    # ### end Alembic commands ###
