"""update

Revision ID: 7c7fd8ec0849
Revises: 2f089f154454
Create Date: 2021-11-25 16:56:53.563623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7fd8ec0849'
down_revision = '2f089f154454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
