# Generated by Django 3.2.5 on 2021-11-10 08:26

from django.db import migrations, models
import django.db.models.deletion
import layer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=layer.models.layer_directory_path, validators=[layer.models.validate_file_extension])),
                ('png_image', models.FileField(upload_to=layer.models.layer_directory_path, validators=[layer.models.validate_png_file_extension])),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
