export { CustomerList } from "./customerList"
export { AddCustomer } from "./addCustomer"
export { EditCustomer } from "./editCustomer"
export { CustomerDetails } from "./customerDetails"
export { LifeEvents } from "./lifeEvents"
