"""Added cognito id column to the User model

Revision ID: 3191f273672e
Revises: 1239d132e5bb
Create Date: 2019-11-14 14:35:42.489267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3191f273672e'
down_revision = '1239d132e5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cognito_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['cognito_id'])
    # ### end Alembic commands ###
    op.execute("INSERT INTO \"user\" (email, first_name, last_name, cognito_id) VALUES ('admin@funnelai.com', 'FunnelAI', 'Admin', '4efff4b5-598a-4fea-aafb-05b32e93bdcb');")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'cognito_id')
    # ### end Alembic commands ###
