"""Added response template schema

Revision ID: 621b995a3829
Revises: ef43da0f32e0
Create Date: 2019-12-17 15:25:56.072611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621b995a3829'
down_revision = 'ef43da0f32e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_initial_response', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_template')
    # ### end Alembic commands ###
