"""Replaced enums due to known bug in graphene-sqlalchemy with reusing enums

Revision ID: 78d54c70f7e1
Revises: 771fe395d53b
Create Date: 2019-11-20 14:55:37.537649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78d54c70f7e1'
down_revision = '771fe395d53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_filter', sa.Column('filter_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'saved_filter', 'filter_type', ['filter_type_id'], ['id'])
    op.drop_column('saved_filter', 'type')
    op.add_column('user_filter', sa.Column('filter_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_filter', 'filter_type', ['filter_type_id'], ['id'])
    op.drop_column('user_filter', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_filter', sa.Column('type', postgresql.ENUM('MULTISELECT', 'SELECT', 'TEXT', name='filtergrouptype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_filter', type_='foreignkey')
    op.drop_column('user_filter', 'filter_type_id')
    op.add_column('saved_filter', sa.Column('type', postgresql.ENUM('MULTISELECT', 'SELECT', 'TEXT', name='filtergrouptype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'saved_filter', type_='foreignkey')
    op.drop_column('saved_filter', 'filter_type_id')
    # ### end Alembic commands ###
