"""added events and objects

Revision ID: 9929932ec8be
Revises: 0951e4a3dadc
Create Date: 2019-12-01 13:01:10.859981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9929932ec8be'
down_revision = '0951e4a3dadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('display', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'type')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('verb', sa.String(), nullable=True),
    sa.Column('direct_object_id', sa.Integer(), nullable=True),
    sa.Column('indirect_object_id', sa.Integer(), nullable=True),
    sa.Column('prepositional_object_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['direct_object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['indirect_object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['prepositional_object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('object')
    # ### end Alembic commands ###
