"""Added deal and conversation_entry tables

Revision ID: b063b8daf077
Revises: 25644323b1cf
Create Date: 2019-12-09 18:11:01.356222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b063b8daf077'
down_revision = '25644323b1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('aingine_data_id', sa.Integer(), nullable=False),
    sa.Column('aingine_user_id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('strength', sa.Enum('HOT', 'WARM', 'COLD', name='dealstrength'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEAL_WON', 'DEAL_LOST', 'PUSHED_CRM', 'EXPIRED', 'ARCHIVED', name='dealstatus'), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('followup_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ORIGINAL', 'SENT', 'RECEIVED', 'NOTE', name='entrytype'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('author_ai_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_entry')
    op.drop_table('deal')
    # ### end Alembic commands ###
