"""Add 
duration column

Revision ID: c9b221976afc
Revises: 9929932ec8be
Create Date: 2019-12-02 12:20:50.268167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b221976afc'
down_revision = '9929932ec8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'duration')
    # ### end Alembic commands ###
