"""Added aingine data id to conversation table

Revision ID: ef43da0f32e0
Revises: b063b8daf077
Create Date: 2019-12-09 19:10:39.193402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef43da0f32e0'
down_revision = 'b063b8daf077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_entry', sa.Column('aingine_data_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_entry', 'aingine_data_id')
    # ### end Alembic commands ###
