"""Added compnay admin permision to roles

Revision ID: 0f4d6392bc34
Revises: 3d04620bb8db
Create Date: 2020-01-23 12:10:51.936196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4d6392bc34'
down_revision = '3d04620bb8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('is_company_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'is_company_admin')
    # ### end Alembic commands ###
