"""added_team_member_relation_with_team

Revision ID: 608dfb7c57cb
Revises: 3ff6176f0f09
Create Date: 2020-01-03 13:45:05.952738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608dfb7c57cb'
down_revision = '3ff6176f0f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_member', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team_member', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.drop_column('team_member', 'team_id')
    # ### end Alembic commands ###
