"""added_team_relation_with_company

Revision ID: 125a1ef3c373
Revises: 608dfb7c57cb
Create Date: 2020-01-03 14:01:23.059922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125a1ef3c373'
down_revision = '608dfb7c57cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'company_id')
    # ### end Alembic commands ###
