"""Added VS CRM changes

Revision ID: 64dd2a32c451
Revises: 42c2a32b33c3
Create Date: 2020-06-25 05:22:12.588846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dd2a32c451'
down_revision = '42c2a32b33c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vin_solutions_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vs_user_id', sa.Integer(), nullable=False),
    sa.Column('crm_integration_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crm_integration_id'], ['crm_integration.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('crm_lead', sa.Column('contact_id', sa.String(), nullable=True))
    op.add_column('crm_lead', sa.Column('account_id', sa.String(), nullable=True),)
    #op.create_table('crm_lead',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('created_at', sa.DateTime(), nullable=True),
    #sa.Column('deal_id', sa.Integer(), nullable=False),
    #sa.Column('lead_id', sa.String(), nullable=True),
    #sa.Column('customer_id', sa.String(), nullable=True),
    #sa.Column('dealer_id', sa.String(), nullable=True),
    #sa.Column('contact_id', sa.String(), nullable=True),
    #sa.Column('account_id', sa.String(), nullable=True),
    #sa.Column('crm_integration_id', sa.Integer(), nullable=False),
    #sa.ForeignKeyConstraint(['crm_integration_id'], ['crm_integration.id'], ),
    #sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    #sa.PrimaryKeyConstraint('id')
    #)
    #op.add_column('crm_integration', sa.Column('active', sa.Boolean(), nullable=True))
    #op.add_column('crm_integration', sa.Column('crm_dealer_id', sa.String(), nullable=True))
    op.add_column('crm_integration', sa.Column('vs_lead_source_id', sa.String(), nullable=True))
    #op.drop_column('crm_integration', 'vin_dealer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('crm_integration', sa.Column('vin_dealer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('crm_integration', 'vs_lead_source_id')
    #op.drop_column('crm_integration', 'crm_dealer_id')
    #op.drop_column('crm_integration', 'active')
    #op.drop_table('crm_lead')
    op.drop_table('vin_solutions_user')
    # ### end Alembic commands ###
