"""Add on delete cascade to user filters to allow deletion of filter types

Revision ID: 983333de41cc
Revises: 205759953294
Create Date: 2020-01-23 21:15:15.266291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983333de41cc'
down_revision = '205759953294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_filter_filter_type_id_fkey', 'user_filter', type_='foreignkey')
    op.create_foreign_key(None, 'user_filter', 'filter_type', ['filter_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_filter', type_='foreignkey')
    op.create_foreign_key('user_filter_filter_type_id_fkey', 'user_filter', 'filter_type', ['filter_type_id'], ['id'])
    # ### end Alembic commands ###
