"""added_filter_set_type

Revision ID: 2b0fdda93092
Revises: ad5c11dd5a81
Create Date: 2020-02-12 10:24:42.206214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0fdda93092'
down_revision = 'ad5c11dd5a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter_set', sa.Column('set_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter_set', 'set_type')
    # ### end Alembic commands ###
