"""Added tags to deal table

Revision ID: dfafdcb29227
Revises: 3dd2a8be9b17
Create Date: 2020-01-31 17:41:18.968258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfafdcb29227'
down_revision = '3dd2a8be9b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'tags')
    # ### end Alembic commands ###
