"""Added query string field to selection options for es queries

Revision ID: f06d5809b45d
Revises: 3899ab2ddfc6
Create Date: 2020-01-20 21:04:43.018434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06d5809b45d'
down_revision = '3899ab2ddfc6'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('ALTER TABLE filter_type alter column filter_field type varchar;')
    op.execute("DROP TYPE filterfield;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selection_option', sa.Column('query', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    op.execute("CREATE type filterfield as enum ('TAGS', 'BODY', 'LOCATION');")
    op.execute('ALTER TABLE filter_type alter column filter_field type filterfield using filter_field::text::filterfield;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selection_option', 'query')
    # ### end Alembic commands ###
