"""added_notification_config_detail

Revision ID: 59f1953bdda7
Revises: 28739dbb7ab0
Create Date: 2020-07-14 18:29:07.426494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f1953bdda7'
down_revision = '28739dbb7ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_config_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(), nullable=True),
    sa.Column('filter_set_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('notification_config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filter_set_id'], ['filter_set.id'], ),
    sa.ForeignKeyConstraint(['notification_config_id'], ['notification_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notification_config', sa.Column('app', sa.Boolean(), nullable=True))
    op.add_column('notification_config', sa.Column('email', sa.Boolean(), nullable=True))
    op.add_column('notification_config', sa.Column('interval', sa.String(), nullable=True))
    op.add_column('notification_config', sa.Column('sms', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_config', 'sms')
    op.drop_column('notification_config', 'interval')
    op.drop_column('notification_config', 'email')
    op.drop_column('notification_config', 'app')
    op.drop_table('notification_config_detail')
    # ### end Alembic commands ###
