"""added_export_congig_and_file

Revision ID: ee360b86db9e
Revises: 67662aea971a
Create Date: 2020-03-06 10:51:07.311756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee360b86db9e'
down_revision = '67662aea971a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('minimum_count', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('last_exported', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_config_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['export_config_id'], ['export_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_filter', sa.Column('export_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_filter', 'export_config', ['export_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_filter', type_='foreignkey')
    op.drop_column('user_filter', 'export_config_id')
    op.drop_table('export')
    op.drop_table('export_config')
    # ### end Alembic commands ###
