"""Added notification config table

Revision ID: cfe54669f1a2
Revises: 3a020f444584
Create Date: 2020-02-06 21:49:50.090016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe54669f1a2'
down_revision = '3a020f444584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notifications_allowed', sa.Boolean(), nullable=True),
    sa.Column('dnd_start', sa.Time(), nullable=True),
    sa.Column('dnd_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_config')
    # ### end Alembic commands ###
