"""Added additional columns to conversation entry table

Revision ID: 3dd2a8be9b17
Revises: 792d99bd2632
Create Date: 2020-01-31 17:16:41.275955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd2a8be9b17'
down_revision = '792d99bd2632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_entry', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('conversation_entry', sa.Column('is_temp', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_entry', 'is_temp')
    op.drop_column('conversation_entry', 'date_created')
    # ### end Alembic commands ###
