"""added_responses_to_notifications

Revision ID: 3b160b91da16
Revises: 35573c5b4c8d
Create Date: 2020-07-23 18:26:29.722102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b160b91da16'
down_revision = '35573c5b4c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_config', sa.Column('responses', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_config', 'responses')
    # ### end Alembic commands ###
