"""Renamed vin_dealer_id colum crm_integration tbl

Revision ID: 221e142263da
Revises: 247b506a0176
Create Date: 2020-04-12 21:21:35.848691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221e142263da'
down_revision = '247b506a0176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_integration', sa.Column('crm_dealer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('crm_integration', 'vin_dealer_id')
    with op.get_context().autocommit_block():
        op.execute(f"ALTER TYPE crmintegrationtype ADD VALUE IF NOT EXISTS 'DS' BEFORE 'VIN'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_integration', sa.Column('vin_dealer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('crm_integration', 'crm_dealer_id')
    with op.get_context().autocommit_block():
        op.execute(f"CREATE TYPE crmintegrationtype_new AS ENUM('ADF', 'VIN');")
        op.execute(f"ALTER TABLE crm_integration ALTER COLUMN integration_type TYPE crmintegrationtype_new USING (integration_type::text::crmintegrationtype_new)")
        op.execute(f"DROP TYPE crmintegrationtype;")
        op.execute(f"ALTER TYPE crmintegrationtype_new RENAME TO crmintegrationtype;")
    # ### end Alembic commands ###
