"""Added allow notifications column to deals

Revision ID: ad5c11dd5a81
Revises: cfe54669f1a2
Create Date: 2020-02-06 23:34:08.284110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5c11dd5a81'
down_revision = 'cfe54669f1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('allow_notifications', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'allow_notifications')
    # ### end Alembic commands ###
