"""updated_export_config_columns

Revision ID: a824328459a8
Revises: f81a95f0ad97
Create Date: 2020-03-13 15:24:24.662739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a824328459a8'
down_revision = 'f81a95f0ad97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_config', sa.Column('ad_hoc', sa.Boolean(), nullable=True))
    op.add_column('export_config', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('export_config', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('export_config', sa.Column('frequency', sa.Integer(), nullable=True))
    op.add_column('export_config', sa.Column('last_run', sa.DateTime(), nullable=True))
    op.add_column('export_config', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'export_config', 'company', ['company_id'], ['id'])
    op.drop_column('export_config', 'platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_config', sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'export_config', type_='foreignkey')
    op.drop_column('export_config', 'start_date')
    op.drop_column('export_config', 'last_run')
    op.drop_column('export_config', 'frequency')
    op.drop_column('export_config', 'end_date')
    op.drop_column('export_config', 'company_id')
    op.drop_column('export_config', 'ad_hoc')
    # ### end Alembic commands ###
