"""added_post_type

Revision ID: 473461c50dfa
Revises: c0ddb0e28b12
Create Date: 2020-05-12 15:58:56.823684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473461c50dfa'
down_revision = 'c0ddb0e28b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('post_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'post_type')
    # ### end Alembic commands ###
