"""Added auto analytics permission to roles

Revision ID: 4c299a8e952a
Revises: 9b5313dc7fdf
Create Date: 2020-02-26 13:40:51.801820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c299a8e952a'
down_revision = '9b5313dc7fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('can_view_auto_analytics', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'can_view_auto_analytics')
    # ### end Alembic commands ###
