"""Added is_disabled column to UserAccounts

Revision ID: 506125170ba0
Revises: 6f693a87b86d
Create Date: 2020-09-30 13:21:16.304999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '506125170ba0'
down_revision = '6f693a87b86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('is_disabled', sa.Boolean(), nullable=True))



    status = postgresql.ENUM('PENDING', 'ACTIVATED', name='status')
    op.alter_column('user_accounts', 'status',
               existing_type=status,
               type_=sa.VARCHAR(length=64), postgresql_using='status::status')
    status.drop(op.get_bind())

    status = postgresql.ENUM('PENDING', 'ACTIVATED', 'DISABLED', name='status')
    status.create(op.get_bind())
    op.alter_column('user_accounts', 'status',
               existing_type=sa.VARCHAR(length=64),
               type_=status, postgresql_using='status::status')



    op.execute("UPDATE user_accounts SET is_disabled = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'is_disabled')

    status = postgresql.ENUM('PENDING', 'ACTIVATED', 'DISABLED', name='status')
    op.alter_column('user_accounts', 'status',
               existing_type=status,
               type_=sa.VARCHAR(length=64), postgresql_using='status::status')
    status.drop(op.get_bind())

    status = postgresql.ENUM('PENDING', 'ACTIVATED', name='status')
    status.create(op.get_bind())
    op.alter_column('user_accounts', 'status',
               existing_type=sa.VARCHAR(length=64),
               type_=status, postgresql_using='status::status')


    # ### end Alembic commands ###
