"""added_deleted_column_to_exports

Revision ID: 247b506a0176
Revises: a95ce8ef45f7
Create Date: 2020-03-24 12:55:08.512688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247b506a0176'
down_revision = 'a95ce8ef45f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('export_config', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_config', 'deleted')
    op.drop_column('export', 'deleted')
    # ### end Alembic commands ###
