"""Added ad export role permission

Revision ID: a95ce8ef45f7
Revises: a824328459a8
Create Date: 2020-03-20 10:52:52.038255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95ce8ef45f7'
down_revision = 'a824328459a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('can_view_ad_export', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'can_view_ad_export')
    # ### end Alembic commands ###
