"""added_user_company_new_fields

Revision ID: 054698e69e36
Revises: 6bd4cd8b5a2e
Create Date: 2020-01-17 09:55:58.322625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054698e69e36'
down_revision = '7bbc5ccc5d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('address_detail', sa.String(), nullable=True))
    op.add_column('company', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('company', sa.Column('profile_pic', sa.String(), nullable=True))
    op.add_column('company', sa.Column('website', sa.String(), nullable=True))
    op.add_column('user', sa.Column('profile_pic', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    op.drop_column('company', 'website')
    op.drop_column('company', 'profile_pic')
    op.drop_column('company', 'industry')
    op.drop_column('company', 'address_detail')
    # ### end Alembic commands ###
