"""added active to response config and source_id to deal table

Revision ID: 87e4026090e7
Revises: 054698e69e36
Create Date: 2020-01-17 22:15:01.765817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e4026090e7'
down_revision = '054698e69e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('source_id', sa.Integer(), nullable=True))
    # op.drop_column('deal', 'aingine_ai_id')
    op.add_column('response_config', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_config', 'active')
    # op.add_column('deal', sa.Column('aingine_ai_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('deal', 'source_id')
    # ### end Alembic commands ###
