"""Added clm permission to role table

Revision ID: 5ba45932cc34
Revises: 2e9277c5c928
Create Date: 2020-05-07 10:17:28.249784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba45932cc34'
down_revision = '2e9277c5c928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('can_view_clm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'can_view_clm')
    # ### end Alembic commands ###
