"""removed uneccassary column from response config

Revision ID: 3899ab2ddfc6
Revises: 87e4026090e7
Create Date: 2020-01-17 22:20:06.959671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3899ab2ddfc6'
down_revision = '87e4026090e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_config', 'thread_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_config', sa.Column('thread_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
