"""Added can_view_gle column

Revision ID: 9ff55ef0cd51
Revises: 6fff55ba6cef
Create Date: 2020-09-07 17:22:07.777835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff55ef0cd51'
down_revision = '6fff55ba6cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('can_view_gle', sa.Boolean(), nullable=True))
    op.alter_column('user_accounts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_accounts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('role', 'can_view_gle')
    # ### end Alembic commands ###
