"""Added CRM Integration models

Revision ID: 3568906ba5d5
Revises: 983333de41cc
Create Date: 2020-01-30 08:32:46.710713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3568906ba5d5'
down_revision = '983333de41cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('integration_type', sa.Enum('ADF', 'VIN', name='crmintegrationtype'), nullable=False),
    sa.Column('adf_email', sa.String(), nullable=True),
    sa.Column('vin_dealer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_integration')
    # ### end Alembic commands ###
