"""Added cascade delete to selection options

Revision ID: 3d04620bb8db
Revises: fd5531abcff0
Create Date: 2020-01-22 23:19:44.380555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d04620bb8db'
down_revision = 'fd5531abcff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_filter_selection_option_id_fkey', 'company_filter', type_='foreignkey')
    op.create_foreign_key(None, 'company_filter', 'selection_option', ['selection_option_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_filter', type_='foreignkey')
    op.create_foreign_key('company_filter_selection_option_id_fkey', 'company_filter', 'selection_option', ['selection_option_id'], ['id'])
    # ### end Alembic commands ###
