"""added_notif_last_run

Revision ID: 35573c5b4c8d
Revises: 59f1953bdda7
Create Date: 2020-07-21 20:27:43.665620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35573c5b4c8d'
down_revision = '59f1953bdda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_config', sa.Column('last_run', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_config', 'last_run')
    # ### end Alembic commands ###
