"""Added screen name to response config and added source url to screenname

Revision ID: 7bbc5ccc5d6a
Revises: 1a3dc8937b6e
Create Date: 2020-01-08 11:50:05.167859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbc5ccc5d6a'
down_revision = '1a3dc8937b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_config', sa.Column('screen_name', sa.String(), nullable=True))
    op.drop_constraint('response_config_screen_name_id_fkey', 'response_config', type_='foreignkey')
    op.drop_column('response_config', 'screen_name_id')
    op.add_column('screen_name', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screen_name', 'source_url')
    op.add_column('response_config', sa.Column('screen_name_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('response_config_screen_name_id_fkey', 'response_config', 'screen_name', ['screen_name_id'], ['id'])
    op.drop_column('response_config', 'screen_name')
    # ### end Alembic commands ###
