"""Added user status column to user

Revision ID: 792d99bd2632
Revises: 983333de41cc
Create Date: 2020-01-28 10:38:46.582729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '792d99bd2632'
down_revision = '983333de41cc'
branch_labels = None
depends_on = None


def upgrade():
    user_status = postgresql.ENUM('PENDING', 'ACTIVATED', name='userstatus')
    user_status.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Enum('PENDING', 'ACTIVATED', name='userstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
    op.execute("DROP TYPE userstatus")
