"""Add on delete cascade to saved filters to allow deletion of filter types

Revision ID: 205759953294
Revises: 9cec67ca7bb0
Create Date: 2020-01-23 19:17:55.110250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205759953294'
down_revision = '9cec67ca7bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('saved_filter_filter_type_id_fkey', 'saved_filter', type_='foreignkey')
    op.create_foreign_key(None, 'saved_filter', 'filter_type', ['filter_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_filter', type_='foreignkey')
    op.create_foreign_key('saved_filter_filter_type_id_fkey', 'saved_filter', 'filter_type', ['filter_type_id'], ['id'])
    # ### end Alembic commands ###
