"""Made company filter dependent tables cascade on delete so admins are able to make changes to them

Revision ID: fd5531abcff0
Revises: f06d5809b45d
Create Date: 2020-01-21 00:17:42.857789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5531abcff0'
down_revision = 'f06d5809b45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('saved_filter_company_filter_id_fkey', 'saved_filter', type_='foreignkey')
    op.create_foreign_key(None, 'saved_filter', 'company_filter', ['company_filter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_filter_company_filter_id_fkey', 'user_filter', type_='foreignkey')
    op.create_foreign_key(None, 'user_filter', 'company_filter', ['company_filter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_filter', type_='foreignkey')
    op.create_foreign_key('user_filter_company_filter_id_fkey', 'user_filter', 'company_filter', ['company_filter_id'], ['id'])
    op.drop_constraint(None, 'saved_filter', type_='foreignkey')
    op.create_foreign_key('saved_filter_company_filter_id_fkey', 'saved_filter', 'company_filter', ['company_filter_id'], ['id'])
    # ### end Alembic commands ###
