"""Added VS lead status mapping table

Revision ID: 9bf3a112aa56
Revises: 67f2f82ae610
Create Date: 2021-10-19 12:49:40.889492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf3a112aa56'
down_revision = '67f2f82ae610'
branch_labels = None
depends_on = None

### Defined enum type and temp type for add & remove field value.
name = 'appointmentstatus'
tmp_name = 'tmp_' + name

old_options = ('SCHEDULED', 'RESCHEDULED', 'CANCELLED', 'NO_SHOWED')
new_options = ('SCHEDULED', 'RESCHEDULED', 'SHOWED', 'CANCELLED', 'NO_SHOWED')

old_type = sa.Enum(*old_options, name = name)
new_type = sa.Enum(*new_options, name = name)

tcr = sa.sql.table('appointment', sa.Column('appointment_status', new_type, nullable=False))
tcr_history = sa.sql.table('appointment_history', sa.Column('appointment_status', new_type, nullable=False))

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vs_lead_status_mapping',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vs_lead_status', sa.String(), nullable=True),
        sa.Column('vs_lead_status_type', sa.String(), nullable=True),
        sa.Column('lead_status_type_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['lead_status_type_id'], ['lead_status_type.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vin_solutions_vehicles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vs_vehicle_id', sa.String(), nullable=False),
        sa.Column('lead_vehicle_of_interest_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['lead_vehicle_of_interest_id'], ['lead_vehicle_of_interest.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vs_extracted_lead', sa.Column('vs_lead_status_mapping_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vs_extracted_lead', 'vs_lead_status_mapping', ['vs_lead_status_mapping_id'], ['id'])
    # ### end Alembic commands ###

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    new_type.create(op.get_bind())
    op.execute('ALTER TABLE appointment ALTER COLUMN appointment_status ' +
               'TYPE ' + name + ' USING appointment_status::text::' + name)
    op.execute('ALTER TABLE appointment_history ALTER COLUMN appointment_status ' +
               'TYPE ' + name + ' USING appointment_status::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)

    op.execute(f"""
                    INSERT INTO vs_lead_status_mapping (vs_lead_status, vs_lead_status_type, lead_status_type_id) VALUES
                            ('ACTIVE_NEW_LEAD', 'ACTIVE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'NEW_LEAD')),
                            ('ACTIVE_NEW_LEAD', 'ACTIVE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'NEW_SMAI_LEAD')),
                            ('ACTIVE_WAITING_FOR_PROSPECT_RESPONSE', 'ACTIVE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'WAITING_FOR_LEAD_RESPONSE')),
                            ('ACTIVE_ACTIVE_LEAD', 'ACTIVE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'UNREAD_MESSAGE_FROM_LEAD')),
                            ('SOLD_ON_ORDER', 'SOLD', (SELECT id FROM lead_status_type WHERE type = 'SOLD' and status = 'ON_ORDER')),
                            ('LOST_LEAD_PROCESS_COMPLETED', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('BAD_BAD_OR_NO_CONTACT_INFORMATION', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'BAD_PHONE_NUMBER')),
                            ('BAD_BAD_OR_NO_CONTACT_INFORMATION', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'BAD_EMAIL')),
                            ('BAD_BAD_OR_NO_CONTACT_INFORMATION', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'BAD_ADDRESS')),
                            ('BAD_PROSPECT_CLAIMS_NEVER_SUBMITTED', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('BAD_UNDERAGE_PROSPECT', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('BAD_DUPLICATE_LEAD', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'DUPLICATE')),
                            ('SOLD_PENDING_FINANCE', 'SOLD', (SELECT id FROM lead_status_type WHERE type = 'SOLD' and status = 'PENDING')),
                            ('SOLD_DELIVERED', 'SOLD', (SELECT id FROM lead_status_type WHERE type = 'SOLD' and status = 'DELIVERED')),
                            ('LOST_DID_NOT_RESPOND', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'NO_RESPONSE')),
                            ('LOST_BAD_CREDIT', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'BAD_CREDIT')),
                            ('LOST_NO_AGREEMENT_REACHED', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('ACTIVE_SET_APPOINTMENT', 'ACTIVE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'APPOINTMENT_SCHEDULED')),
                            ('ACTIVE_EMAIL_INBOX', 'ACTIVE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'OTHER')),
                            ('LOST_IMPORT_LEAD', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('LOST_PURCHASED_SAME_BRAND_DIFFERENT_DEALER', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'BOUGHT_ELSEWHERE')),
                            ('LOST_PURCHASED_DIFFERENT_BRAND_DIFFERENT_DEALER', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'BOUGHT_ELSEWHERE')),
                            ('LOST_WORKING_WITH_OTHER_SALESPERSON', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('LOST_REQUESTED_NO_FURTHER_CONTACT', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('LOST_PURCHASED_FROM_PRIVATE_PARTY', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('LOST_OUT_OF_MARKET', 'LOST', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'NO_LONGER_IN_MARKET')),
                            ('BAD_DEALER_TEST_LEAD', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('BAD_INCORRECT_CUSTOMER_PHONE', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'BAD_PHONE_NUMBER')),
                            ('BAD_NO_INTENT_TO_BUY', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'NOT_INTERESTED_TO_BUY')),
                            ('BAD_INCENTIVIZED', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('BAD_SHOPPING_OUT_OF_AREA', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('BAD_NO_CONTACT_IN_FIVE_DAYS', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('SERVICE_COMPLETE', 'COMPLETE', (SELECT id FROM lead_status_type WHERE type = 'SOLD' and status = 'ON_ORDER')),
                            ('SERVICE_APPOINTMENT_SCHEDULED', 'ACTIVE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'APPOINTMENT_SCHEDULED')),
                            ('SERVICE_APPOINTMENT_MISSED', 'ACTIVE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'APPOINTMENT_MISSED')),
                            ('SERVICE_STARTED', 'ACTIVE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'APPOINTMENT_CONFIRMED')),
                            ('SERVICE_REJECTED', 'ACTIVE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'APPOINTMENT_CANCELED')),
                            ('NON_CUSTOMER_INITIATED_LEAD', 'BAD', (SELECT id FROM lead_status_type WHERE type = 'LOST' and status = 'OTHER')),
                            ('SERVICE_APPOINTMENT_CANCELED', 'COMPLETE', (SELECT id FROM lead_status_type WHERE type = 'ACTIVE' and status = 'APPOINTMENT_CANCELED'))
                            ;
                """)

    op.execute("""
                    UPDATE "user" SET first_name = 'Otto', last_name = '' WHERE first_name = 'SMAI';
                """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vs_extracted_lead_vs_lead_status_mapping_id_fkey', 'vs_extracted_lead', type_='foreignkey')
    op.drop_column('vs_extracted_lead', 'vs_lead_status_mapping_id')
    op.drop_table('vin_solutions_vehicles')
    op.drop_table('vs_lead_status_mapping')
    # ### end Alembic commands ###

    # Convert 'SHOWED' appointment_status into 'SCHEDULED'
    op.execute(tcr.update().where(tcr.c.appointment_status=='SHOWED')
               .values(appointment_status='SCHEDULED'))

    op.execute(tcr_history.update().where(tcr_history.c.appointment_status=='SHOWED')
               .values(appointment_status='SCHEDULED'))

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    old_type.create(op.get_bind())
    op.execute('ALTER TABLE appointment ALTER COLUMN appointment_status ' +
               'TYPE ' + name + ' USING appointment_status::text::' + name)
    op.execute('ALTER TABLE appointment_history ALTER COLUMN appointment_status ' +
               'TYPE ' + name + ' USING appointment_status::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)
