"""Added FCM device table for user

Revision ID: 101bcf12a7b3
Revises: bfbdd5f2bbfe
Create Date: 2021-11-08 16:33:55.380372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101bcf12a7b3'
down_revision = 'bfbdd5f2bbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IOS', 'ANDROID', 'WEB', name='device_types'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fcm_device')
    # ### end Alembic commands ###

    op.execute("DROP TYPE device_types;")
    