"""Added Salesforce table

Revision ID: 7530ce00ce54
Revises: 54852a2b4ee5
Create Date: 2021-11-23 16:39:52.116085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7530ce00ce54'
down_revision = '54852a2b4ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sf_extract_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dealer_id', sa.String(length=16), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('extract_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sf_lead_source',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dealer_id', sa.String(length=16), nullable=False),
        sa.Column('lead_source_id', sa.Integer(), nullable=True),
        sa.Column('sf_lead_source_id', sa.String(), nullable=False),
        sa.Column('sf_lead_source_name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sf_lead_source_id')
    )
    op.create_table('sf_lead_status_mapping',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sf_lead_status_id', sa.String(), nullable=True),
        sa.Column('sf_lead_status', sa.String(), nullable=True),
        sa.Column('lead_status_type_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['lead_status_type_id'], ['lead_status_type.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sf_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('sf_user_id', sa.String(), nullable=False),
        sa.Column('crm_integration_id', sa.Integer(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['crm_integration_id'], ['crm_integration.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sf_extracted_lead',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sf_extract_history_id', sa.Integer(), nullable=False),
        sa.Column('dealer_id', sa.String(length=16), nullable=False),
        sa.Column('sf_lead_id', sa.String(), nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=False),
        sa.Column('sf_lead_status', sa.String(), nullable=True),
        sa.Column('sf_create_date', sa.DateTime(), nullable=True),
        sa.Column('sf_modified_date', sa.DateTime(), nullable=True),
        sa.Column('sf_has_opted_out_of_email', sa.Boolean(), nullable=True),
        sa.Column('sf_lead_source_id', sa.Integer(), nullable=True),
        sa.Column('sf_user_id', sa.Integer(), nullable=True),
        sa.Column('sf_lead_status_mapping_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['sf_extract_history_id'], ['sf_extract_history.id'], ),
        sa.ForeignKeyConstraint(['sf_lead_source_id'], ['sf_lead_source.id'], ),
        sa.ForeignKeyConstraint(['sf_lead_status_mapping_id'], ['sf_lead_status_mapping.id'], ),
        sa.ForeignKeyConstraint(['sf_user_id'], ['sf_user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sf_lead_id')
    )
    op.create_table('sf_vehicles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sf_vehicle_id', sa.String(), nullable=False),
        sa.Column('lead_vehicle_of_interest_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['lead_vehicle_of_interest_id'], ['lead_vehicle_of_interest.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sf_appointment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sf_event_id', sa.String(), nullable=False),
        sa.Column('appointment_id', sa.Integer(), nullable=True),
        sa.Column('sf_extracted_lead_id', sa.Integer(), nullable=True),
        sa.Column('sf_lead_source_id', sa.Integer(), nullable=True),
        sa.Column('sf_user_id', sa.Integer(), nullable=True),
        sa.Column('type', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
        sa.ForeignKeyConstraint(['sf_extracted_lead_id'], ['sf_extracted_lead.id'], ),
        sa.ForeignKeyConstraint(['sf_lead_source_id'], ['sf_lead_source.id'], ),
        sa.ForeignKeyConstraint(['sf_user_id'], ['sf_user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sf_event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sf_appointment')
    op.drop_table('sf_vehicles')
    op.drop_table('sf_extracted_lead')
    op.drop_table('sf_user')
    op.drop_table('sf_lead_status_mapping')
    op.drop_table('sf_lead_source')
    op.drop_table('sf_extract_history')
    # ### end Alembic commands ###
