"""Added campaign models

Revision ID: 061fe4eb829d
Revises: e53994ab12c4
Create Date: 2021-07-13 15:52:20.791457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061fe4eb829d'
down_revision = 'e53994ab12c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('active_ind', sa.Boolean(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('ONCE', 'REPEAT', name='scheduletype'), nullable=False),
    sa.Column('numeric_value', sa.Integer(), nullable=True),
    sa.Column('temporal_value', sa.Enum('SECONDS', 'MINUTES', 'HOURS', 'DAYS', 'WEEKS', 'MONTHS', name='temporaltype'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('DEFAULT', 'SOURCE', 'LEAD','FILE', name='campaigntype'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('template_text', sa.String(), nullable=True),
    sa.Column('active_ind', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['campaign_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_templates')
    op.drop_table('campaign_selections')
    op.drop_table('campaign_schedules')
    op.drop_table('campaign')
    # ### end Alembic commands ###
    op.execute("DROP TYPE scheduletype;")
    op.execute("DROP TYPE temporaltype;")
    op.execute("DROP TYPE campaigntype;")
