"""Added scheduled messages

Revision ID: 77c8fd2825f4
Revises: 2e1b12c7ae0c
Create Date: 2021-08-09 14:19:12.239751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c8fd2825f4'
down_revision = '2e1b12c7ae0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('scheduled_seconds', sa.Integer(), nullable=True),
    sa.Column('repeat_scheduled_seconds', sa.Integer(), nullable=True),
    sa.Column('execution_arn', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_messages')
    # ### end Alembic commands ###
