"""Added is active and is deleted field into template and indexing in message

Revision ID: e9e7d3e43baf
Revises: 3e2bded983c4
Create Date: 2021-09-30 23:25:54.191445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e7d3e43baf'
down_revision = '3e2bded983c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_message_template', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('engagement_message_template', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_message_campaign_id'), 'message', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_message_lead_id'), 'message', ['lead_id'], unique=False)
    op.create_index(op.f('ix_message_message_status'), 'message', ['message_status'], unique=False)
    op.create_index(op.f('ix_message_system_user_id'), 'message', ['system_user_id'], unique=False)
    op.create_index(op.f('ix_message_user_id'), 'message', ['user_id'], unique=False)

    op.execute('UPDATE engagement_message_template SET is_active = True')
    op.execute('UPDATE engagement_message_template SET is_deleted = False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_system_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_message_status'), table_name='message')
    op.drop_index(op.f('ix_message_lead_id'), table_name='message')
    op.drop_index(op.f('ix_message_campaign_id'), table_name='message')
    op.drop_column('engagement_message_template', 'is_deleted')
    op.drop_column('engagement_message_template', 'is_active')
    # ### end Alembic commands ###
