"""Added location field in company table

Revision ID: 89625b017730
Revises: 8a9d2f51630e
Create Date: 2021-10-25 12:04:58.291987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89625b017730'
down_revision = '8a9d2f51630e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('location_link', sa.String(), nullable=True))
    op.add_column('company', sa.Column('is_optin_consent_method', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute(f"""UPDATE company SET is_optin_consent_method = False;""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'is_optin_consent_method')
    op.drop_column('company', 'location_link')
    # ### end Alembic commands ###
