"""Created crm pull processing table

Revision ID: d9c35da38236
Revises: 4867bf2ba7bb
Create Date: 2021-09-16 19:19:02.181491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c35da38236'
down_revision = '4867bf2ba7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_pull_processing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lock', sa.Boolean(), nullable=True),
    sa.Column('last_pull_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_successfull_created_utc', sa.DateTime(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['integration_id'], ['crm_integration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_pull_processing')
    # ### end Alembic commands ###
