"""Added Region and Location models

Revision ID: 8a5bfb765910
Revises: 70d7011842ab
Create Date: 2021-12-03 20:40:43.513752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5bfb765910'
down_revision = '70d7011842ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'location')
    # ### end Alembic commands ###
