"""Added engagement module permisson in Role table

Revision ID: 2e1b12c7ae0c
Revises: 755a2f9392aa
Create Date: 2021-08-06 10:54:00.554418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1b12c7ae0c'
down_revision = '755a2f9392aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('can_view_engagements', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'can_view_engagements')
    # ### end Alembic commands ###
