"""Added is_deleted field into twilio phone service table

Revision ID: 3e2bded983c4
Revises: aa649061d7a5
Create Date: 2021-09-29 12:04:08.810345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2bded983c4'
down_revision = 'aa649061d7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twilio_phone_service', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute('UPDATE twilio_phone_service SET is_deleted = False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twilio_phone_service', 'is_deleted')
    # ### end Alembic commands ###
