"""Added Region and Location models

Revision ID: 70d7011842ab
Revises: f87a0c0e6fe6
Create Date: 2021-12-02 12:43:01.687749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d7011842ab'
down_revision = 'f87a0c0e6fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=True),
        sa.Column('region_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('address_line_1', sa.String(), nullable=True),
        sa.Column('address_line_2', sa.String(), nullable=True),
        sa.Column('city', sa.String(), nullable=True),
        sa.Column('state', sa.String(), nullable=True),
        sa.Column('postal_code', sa.String(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.Column('geo_link', sa.String(), nullable=True),
        sa.Column('website', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('timezone', sa.String(), nullable=True),
        sa.Column('location_type', sa.String(), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
        sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sf_location',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('location_id', sa.Integer(), nullable=False),
        sa.Column('sf_location_id', sa.String(), nullable=False),
        sa.Column('crm_integration_id', sa.Integer(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['crm_integration_id'], ['crm_integration.id'], ),
        sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointment', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment', 'location', ['location_id'], ['id'])
    op.drop_column('appointment', 'location')
    op.add_column('appointment_history', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('company_working_hours', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company_working_hours', 'location', ['location_id'], ['id'])
    op.add_column('leads', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'location', ['location_id'], ['id'])
    op.add_column('sf_extracted_lead', sa.Column('sf_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sf_extracted_lead', 'sf_location', ['sf_location_id'], ['id'])
    op.add_column('user', sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'location', ['location_id'], ['id'])
    op.create_foreign_key(None, 'user', 'region', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_location_id_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_region_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'location_id')
    op.drop_column('user', 'region_id')
    op.drop_constraint('sf_extracted_lead_sf_location_id_fkey', 'sf_extracted_lead', type_='foreignkey')
    op.drop_column('sf_extracted_lead', 'sf_location_id')
    op.drop_constraint('leads_location_id_fkey', 'leads', type_='foreignkey')
    op.drop_column('leads', 'location_id')
    op.drop_constraint('company_working_hours_location_id_fkey', 'company_working_hours', type_='foreignkey')
    op.drop_column('company_working_hours', 'location_id')
    op.drop_column('appointment_history', 'location_id')
    op.add_column('appointment', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('appointment_location_id_fkey', 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'location_id')
    op.drop_table('sf_location')
    op.drop_table('location')
    op.drop_table('region')
    # ### end Alembic commands ###
