"""Added Lead User Mapping

Revision ID: 83dfb2b8d8be
Revises: 8a5bfb765910
Create Date: 2021-12-06 12:10:32.978812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dfb2b8d8be'
down_revision = '8a5bfb765910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('sf_extracted_lead_sf_lead_id_key', 'sf_extracted_lead', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sf_extracted_lead_sf_lead_id_key', 'sf_extracted_lead', ['sf_lead_id'])
    op.drop_table('lead_user')
    # ### end Alembic commands ###
