"""Added campaign lead summary table

Revision ID: a2dcdfc467c2
Revises: 6ec5bd116e9a
Create Date: 2021-08-10 16:43:58.558000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dcdfc467c2'
down_revision = '6ec5bd116e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_lead_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('last_message_sent_date', sa.DateTime(), nullable=True),
    sa.Column('last_message_received_date', sa.DateTime(), nullable=True),
    sa.Column('num_attempts_before_response', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UNCONTACTED', 'QUEUED', 'SENT', 'FAILED', 'DELIVERED', 'RESPONDED', 'ENGAGED', 'OPT_OUT', name='campaignleadstatustype'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_lead_summary')
    # ### end Alembic commands ###
