"""ReviewMessageTemplate model fields company_id, user_id, file_name, file_location added

Revision ID: 2f4178a28ac7
Revises: 3e79e031c0a0
Create Date: 2021-12-10 11:18:38.415744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4178a28ac7'
down_revision = '3e79e031c0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_message_template', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('review_message_template', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('review_message_template', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('review_message_template', sa.Column('file_location', sa.String(), nullable=True))
    op.create_foreign_key(None, 'review_message_template', 'company', ['company_id'], ['id'])
    op.create_foreign_key(None, 'review_message_template', 'user', ['user_id'], ['id'])
    op.drop_column('review_message_template', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_message_template', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review_message_template', type_='foreignkey')
    op.drop_constraint(None, 'review_message_template', type_='foreignkey')
    op.drop_column('review_message_template', 'file_location')
    op.drop_column('review_message_template', 'file_name')
    op.drop_column('review_message_template', 'user_id')
    op.drop_column('review_message_template', 'company_id')
    # ### end Alembic commands ###
