"""Added active field into Lead status history

Revision ID: 20766a423ec2
Revises: e9e7d3e43baf
Create Date: 2021-10-05 17:19:29.207077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20766a423ec2'
down_revision = 'e9e7d3e43baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('DEFAULT', 'CUSTOM', 'NEW_LEAD', name='campaignmanagetype'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_status_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('ACTIVE', 'LOST', 'SOLD', name='leadtype'), nullable=False),
        sa.Column('status', sa.String(length=100), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_status_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=False),
        sa.Column('lead_status_type_id', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
        sa.ForeignKeyConstraint(['lead_status_type_id'], ['lead_status_type.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaign', sa.Column('campaign_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campaign', 'campaign_types', ['campaign_type_id'], ['id'])
    # ### end Alembic commands ###

    op.execute(f"""
                    INSERT INTO lead_status_type (type, status) VALUES
                            ('ACTIVE', 'NEW_LEAD'),
                            ('ACTIVE', 'NEW_SMAI_LEAD'),
                            ('ACTIVE', 'WAITING_FOR_LEAD_RESPONSE'),
                            ('ACTIVE', 'UNREAD_MESSAGE_FROM_LEAD'),
                            ('ACTIVE', 'WAITING_FOR_DEALER_RESPONSE'),
                            ('ACTIVE', 'APPOINTMENT_SCHEDULED'),
                            ('ACTIVE', 'APPOINTMENT_CONFIRMED'),
                            ('ACTIVE', 'APPOINTMENT_MISSED'),
                            ('ACTIVE', 'APPOINTMENT_SHOWED'),
                            ('ACTIVE', 'APPOINTMENT_CANCELED'),
                            ('ACTIVE', 'OTHER'),
                            ('LOST', 'DUPLICATE'),
                            ('LOST', 'BAD_PHONE_NUMBER'),
                            ('LOST', 'BAD_EMAIL'),
                            ('LOST', 'BAD_ADDRESS'),
                            ('LOST', 'BAD_CREDIT'),
                            ('LOST', 'NOT_INTERESTED_TO_BUY'),
                            ('LOST', 'NOT_INTERESTED_TO_SELL'),
                            ('LOST', 'NOT_QUALIFIED'),
                            ('LOST', 'NO_RESPONSE'),
                            ('LOST', 'NO_LONGER_IN_MARKET'),
                            ('LOST', 'SMS_OPTED_OUT'),
                            ('LOST', 'SMS_OPT_IN_LAPSED'),
                            ('LOST', 'BOUGHT_ELSEWHERE'),
                            ('LOST', 'OTHER'),
                            ('SOLD', 'ON_ORDER'),
                            ('SOLD', 'PENDING'),
                            ('SOLD', 'DELIVERED'),
                            ('SOLD', 'OTHER');
                """)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campaign_campaign_type_id_fkey', 'campaign', type_='foreignkey')
    op.drop_column('campaign', 'campaign_type_id')
    op.drop_table('lead_status_history')
    op.drop_table('lead_status_type')
    op.drop_table('campaign_types')
    # ### end Alembic commands ###

    op.execute("DROP TYPE campaignmanagetype;")
    op.execute("DROP TYPE leadtype;")
