"""Add appointment ID in nudge activity

Revision ID: e7e5f36765b1
Revises: 207d35597904
Create Date: 2021-11-17 16:02:43.328152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e5f36765b1'
down_revision = '207d35597904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nudge_activity', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nudge_activity', 'appointment', ['appointment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nudge_activity_appointment_id_fkey', 'nudge_activity', type_='foreignkey')
    op.drop_column('nudge_activity', 'appointment_id')
    # ### end Alembic commands ###
