"""Added lead notes and vehicle of interest tables

Revision ID: 17091df7d72b
Revises: 75c04620fd88
Create Date: 2021-10-07 12:45:25.031573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '17091df7d72b'
down_revision = '75c04620fd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_of_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('trim', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    customer_interest_type = postgresql.ENUM('BUY', 'SELL', 'TRADE', 'NONE', name='customerinteresttype')
    customer_interest_type.create(op.get_bind())

    op.add_column('lead_vehicle_of_interest', sa.Column('customer_interest', sa.Enum('BUY', 'SELL', 'TRADE', 'NONE', name='customerinteresttype'), nullable=True))
    op.add_column('leads', sa.Column('other_source', sa.String(length=50), nullable=True))

    op.execute(f"""
                    INSERT INTO lead_source (name, is_source) VALUES
                            ('SMAI', false) 
                """)
    op.execute(f""" UPDATE lead_source SET name = 'Other' WHERE name='Unknown' """)

    op.execute(f"""
                    INSERT INTO vehicle_of_interest ("year", model, make) SELECT DISTINCT  "year", model , make FROM lead_vehicle_of_interest WHERE "year" IS NOT NULL AND make IS NOT NULL AND model IS NOT NULL
                """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'other_source')
    op.drop_column('lead_vehicle_of_interest', 'customer_interest')
    op.drop_table('lead_notes')
    op.drop_table('vehicle_of_interest')

    op.execute("DROP TYPE customerinteresttype;")

    op.execute(f""" DELETE FROM lead_source WHERE name='SMAI' """)
    op.execute(f""" UPDATE lead_source SET name = 'Unknown' WHERE name='Other' """)
    # ### end Alembic commands ###
