"""Added prioritize field in campaign table

Revision ID: 755a2f9392aa
Revises: 165d2fb1f4b8
Create Date: 2021-08-04 15:32:26.704194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755a2f9392aa'
down_revision = '165d2fb1f4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('is_prioritize', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'is_prioritize')
    # ### end Alembic commands ###
