"""Added email_type and phone_type in lead models

Revision ID: 20fbf134b01e
Revises: edaf9b3a3f58
Create Date: 2021-09-01 13:57:05.291499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fbf134b01e'
down_revision = 'edaf9b3a3f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_emails', sa.Column('email_type', sa.String(), nullable=True))
    op.add_column('lead_phones', sa.Column('phone_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_phones', 'phone_type')
    op.drop_column('lead_emails', 'email_type')
    # ### end Alembic commands ###
