"""Added messaging related models

Revision ID: 6de0d0ada5a0
Revises: b0e521d78396
Create Date: 2021-07-19 13:21:57.137816

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '6de0d0ada5a0'
down_revision = 'b0e521d78396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('channel_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_user_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('campaign_template_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('TO_LEAD', 'TO_USER', 'FROM_LEAD', 'FROM_USER', name='messagedirection'), nullable=True),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.Column('date_received', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['campaign_template_id'], ['campaign_templates.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['system_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('from_phone', sa.String(), nullable=True),
    sa.Column('to_phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute(f"INSERT INTO public.user (email, first_name, last_name, company_id, date_created, is_disabled, phone) VALUES ('support@socialminingai.com', 'SMAI', 'Bot', 1, \'{datetime.utcnow()}\', False, '+18443866958');")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_table('message_log')
    op.drop_table('message')
    op.drop_table('channel')
    # ### end Alembic commands ###
    op.execute("DROP TYPE messagedirection;")
    op.execute("DELETE FROM public.user WHERE company_id=1 and first_name='SMAI' and last_name='Bot';")
