"""Added scheduled appointment reminder table

Revision ID: 4867bf2ba7bb
Revises: c402d9ffd3ab
Create Date: 2021-09-13 16:32:17.951221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4867bf2ba7bb'
down_revision = 'c402d9ffd3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_appointment_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('execution_arn', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointment', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    op.add_column('appointment', sa.Column('is_show', sa.Boolean(), nullable=True))
    op.add_column('appointment', sa.Column('appointment_status', sa.Enum('SCHEDULED', 'RESCHEDULED', 'CANCELLED', name='appointmentstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'appointment_status')
    op.drop_column('appointment', 'is_show')
    op.drop_column('appointment', 'is_confirmed')
    op.drop_table('scheduled_appointment_reminder')
    # ### end Alembic commands ###
