"""Added shared company flag in template table

Revision ID: 9ad3a2a2f6d5
Revises: 3162e0cd1c3c
Create Date: 2021-10-14 15:54:12.847153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad3a2a2f6d5'
down_revision = '3162e0cd1c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_message_template', sa.Column('is_company_shared', sa.Boolean(), nullable=True))

    op.execute('UPDATE engagement_message_template SET is_company_shared = True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement_message_template', 'is_company_shared')
    # ### end Alembic commands ###
