"""model Review fields added company and _type

Revision ID: f061208b8752
Revises: 537475765761
Create Date: 2021-12-20 10:55:28.391904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f061208b8752'
down_revision = '537475765761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('company', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('_type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'review', 'company', ['company'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', '_type')
    op.drop_column('review', 'company')
    # ### end Alembic commands ###
