"""Added source relation and note id

Revision ID: f87a0c0e6fe6
Revises: 7530ce00ce54
Create Date: 2021-11-30 11:49:38.074436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87a0c0e6fe6'
down_revision = '7530ce00ce54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sf_extract_history', sa.Column('crm_integration_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sf_extract_history', 'crm_integration', ['crm_integration_id'], ['id'])
    op.drop_column('sf_extract_history', 'dealer_id')
    op.add_column('sf_extracted_lead', sa.Column('crm_integration_id', sa.Integer(), nullable=False))
    op.add_column('sf_extracted_lead', sa.Column('sf_source', sa.String(), nullable=True))
    op.add_column('sf_extracted_lead', sa.Column('sf_converted_date', sa.DateTime(), nullable=True))
    op.add_column('sf_extracted_lead', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('sf_extracted_lead', sa.Column('is_converted', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'sf_extracted_lead', 'crm_integration', ['crm_integration_id'], ['id'])
    op.drop_column('sf_extracted_lead', 'dealer_id')
    op.drop_column('sf_extracted_lead', 'sf_has_opted_out_of_email')
    op.drop_column('sf_lead_source', 'dealer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sf_lead_source', sa.Column('dealer_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('sf_extracted_lead', sa.Column('sf_has_opted_out_of_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sf_extracted_lead', sa.Column('dealer_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint('sf_extracted_lead_crm_integration_id_fkey', 'sf_extracted_lead', type_='foreignkey')
    op.drop_column('sf_extracted_lead', 'is_converted')
    op.drop_column('sf_extracted_lead', 'is_deleted')
    op.drop_column('sf_extracted_lead', 'sf_converted_date')
    op.drop_column('sf_extracted_lead', 'sf_source')
    op.drop_column('sf_extracted_lead', 'crm_integration_id')
    op.add_column('sf_extract_history', sa.Column('dealer_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint('sf_extract_history_crm_integration_id_fkey', 'sf_extract_history', type_='foreignkey')
    op.drop_column('sf_extract_history', 'crm_integration_id')
    # ### end Alembic commands ###
