"""Company nudge related tables

Revision ID: 207d35597904
Revises: 13b8d41a3868
Create Date: 2021-11-17 12:41:15.055539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207d35597904'
down_revision = '13b8d41a3868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nudge_event',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_nudge_event',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nudge_event_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('start_delay', sa.Integer(), nullable=False),
        sa.Column('start_delay_type', sa.Enum('MINUTES', 'HOURS', 'DAYS', name='startdelaytype'), nullable=False),
        sa.Column('frequency', sa.Integer(), nullable=False),
        sa.Column('frequency_type', sa.Enum('MINUTES', 'HOURS', 'DAYS', name='frequencytype'), nullable=False),
        sa.Column('first_template_text', sa.String(), nullable=False),
        sa.Column('reminder_template_text', sa.String(), nullable=False),
        sa.Column('is_sms', sa.Boolean(), nullable=True),
        sa.Column('is_web_push', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
        sa.ForeignKeyConstraint(['nudge_event_id'], ['nudge_event.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nudge_activity',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_nudge_event_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_nudge_event_id'], ['company_nudge_event.id'], ),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nudge_activity_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nudge_activity_id', sa.Integer(), nullable=True),
        sa.Column('execution_arn', sa.String(), nullable=True),
        sa.Column('content', sa.String(), nullable=True),
        sa.Column('trigger_on', sa.DateTime(), nullable=True),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['nudge_activity_id'], ['nudge_activity.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointment', sa.Column('discussed_voi_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment', 'lead_vehicle_of_interest', ['discussed_voi_id'], ['id'])
    op.add_column('appointment_history', sa.Column('discussed_voi_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment_history', 'lead_vehicle_of_interest', ['discussed_voi_id'], ['id'])
    op.add_column('lead_vehicle_of_interest', sa.Column('is_primary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute(f"""
                    INSERT INTO nudge_event (code, title, is_active) VALUES 
                        ('REMINDER_SP_LEAD_MESSAGE', 'Reminding the sales person to respond to lead messages', true),
                        ('REMINDER_SP_UPDATE_PAST_APPOINTMENT_STATUS', 'Reminding the sales person to mark the appointment as showed/no showed', true),
                        ('REMINDER_SP_UPDATE_LEAD_STATUS_TO_LOST', 'Reminding the sales person to change the status of a lead to lost lead', true);
                """)

    op.execute("""UPDATE lead_vehicle_of_interest SET is_primary = true;""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_vehicle_of_interest', 'is_primary')
    op.drop_constraint('appointment_history_discussed_voi_id_fkey', 'appointment_history', type_='foreignkey')
    op.drop_column('appointment_history', 'discussed_voi_id')
    op.drop_constraint('appointment_discussed_voi_id_fkey', 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'discussed_voi_id')
    op.drop_table('nudge_activity_history')
    op.drop_table('nudge_activity')
    op.drop_table('company_nudge_event')
    op.drop_table('nudge_event')
    # ### end Alembic commands ###

    op.execute("DROP TYPE startdelaytype;")
    op.execute("DROP TYPE frequencytype;")
    