"""Added date_created field in campaign lead summary table

Revision ID: d6c83761e35d
Revises: a2dcdfc467c2
Create Date: 2021-08-12 10:59:29.274447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c83761e35d'
down_revision = 'a2dcdfc467c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_lead_summary', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_lead_summary', 'date_created')
    # ### end Alembic commands ###
