"""Added current vehicle field for differntiate current and previous

Revision ID: c402d9ffd3ab
Revises: 1eee6416b4af
Create Date: 2021-09-13 11:26:06.303321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c402d9ffd3ab'
down_revision = '1eee6416b4af'
branch_labels = None
depends_on = None

### Defined enum type and temp type for add & remove field value.
name = 'temporaltype'
tmp_name = 'tmp_' + name

old_options = ('SECONDS', 'MINUTES', 'HOURS', 'DAYS', 'WEEKS', 'MONTHS')
new_options = ('MINUTES', 'HOURS', 'DAYS', 'WEEKS', 'MONTHS')

old_type = sa.Enum(*old_options, name = name)
new_type = sa.Enum(*new_options, name = name)

tcr = sa.sql.table('campaign_schedules', sa.Column('temporal_value', new_type, nullable=False))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_vehicle_of_interest', sa.Column('is_current', sa.Boolean(), nullable=True))

    op.execute('UPDATE lead_vehicle_of_interest SET is_current = True')
    # ### end Alembic commands ###


    # Convert 'SECONDS' temporal_value into 'MINUTES'
    op.execute(tcr.update().where(tcr.c.temporal_value=='SECONDS')
               .values(temporal_value='MINUTES'))

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    new_type.create(op.get_bind())
    op.execute('ALTER TABLE campaign_schedules ALTER COLUMN temporal_value ' +
               'TYPE ' + name + ' USING temporal_value::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_vehicle_of_interest', 'is_current')
    # ### end Alembic commands ###

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    old_type.create(op.get_bind())
    op.execute('ALTER TABLE campaign_schedules ALTER COLUMN temporal_value ' +
               'TYPE ' + name + ' USING temporal_value::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)
