"""Added new field stop conversation for lead

Revision ID: 8a9d2f51630e
Revises: 9bf3a112aa56
Create Date: 2021-10-21 16:39:10.269657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9d2f51630e'
down_revision = '9bf3a112aa56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('disable_conversation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute(f"""UPDATE leads SET disable_conversation = False;""")

    op.execute(f"""
                    INSERT INTO campaign_types (type) VALUES 
                        ('DEFAULT'),
                        ('CUSTOM'),
                        ('NEW_LEAD');
                """)
    
    op.execute(f"""
                    UPDATE campaign SET campaign_type_id = (SELECT id FROM campaign_types WHERE type = 'DEFAULT' LIMIT 1)
                        WHERE name = 'Default';
                """)

    op.execute(f"""
                    UPDATE campaign SET campaign_type_id = (SELECT id FROM campaign_types WHERE type = 'CUSTOM' LIMIT 1)
                        WHERE name != 'Default';
                """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'disable_conversation')
    # ### end Alembic commands ###

    op.execute(f"""UPDATE campaign SET campaign_type_id = NULL;""")
    op.execute(f"""DELETE FROM campaign_types;""")

