"""google facebook link added to company settings model

Revision ID: 537475765761
Revises: 2f4178a28ac7
Create Date: 2021-12-15 14:31:40.770365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537475765761'
down_revision = '2f4178a28ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('facebook_link', sa.String(), nullable=True))
    op.add_column('company', sa.Column('google_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'google_link')
    op.drop_column('company', 'facebook_link')
    # ### end Alembic commands ###
