"""Add after hour logic field in schedule template

Revision ID: f2d15988a02e
Revises: e6422c5b0848
Create Date: 2021-09-21 13:03:07.512286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d15988a02e'
down_revision = 'e6422c5b0848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_templates', sa.Column('after_hour_template_text', sa.String(), nullable=True))
    op.add_column('campaign_templates', sa.Column('is_after_hour', sa.Boolean(), nullable=True))
    op.add_column('company', sa.Column('timezone', sa.String(), nullable=True))

    op.execute('UPDATE campaign_templates SET is_after_hour = True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'timezone')
    op.drop_column('campaign_templates', 'is_after_hour')
    op.drop_column('campaign_templates', 'after_hour_template_text')
    # ### end Alembic commands ###
