"""Added title and sort_order field in campaignschedule table

Revision ID: 612b1d465dea
Revises: c718bc832ac9
Create Date: 2021-08-31 10:29:44.670134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612b1d465dea'
down_revision = 'c718bc832ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_schedules', sa.Column('title', sa.String(), nullable=True))
    op.add_column('campaign_schedules', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_schedules', 'sort_order')
    op.drop_column('campaign_schedules', 'title')
    # ### end Alembic commands ###
