"""make dealid nullable in crm_lead table

Revision ID: 67f2f82ae610
Revises: 9ad3a2a2f6d5
Create Date: 2021-10-15 15:26:40.487370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f2f82ae610'
down_revision = '9ad3a2a2f6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_lead', 'deal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_lead', 'deal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
