"""Added campaign schedule option master table

Revision ID: c61b51e8c002
Revises: 107ddb6c3bd5
Create Date: 2021-07-16 11:29:57.606720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'c61b51e8c002'
down_revision = '107ddb6c3bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_schedules_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', ENUM('ONCE', 'REPEAT', name='scheduletype', create_type=False), nullable=False),
    sa.Column('numeric_value', sa.Integer(), nullable=True),
    sa.Column('temporal_value', ENUM('SECONDS', 'MINUTES', 'HOURS', 'DAYS', 'WEEKS', 'MONTHS', name='temporaltype', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaign_schedules', sa.Column('schedules_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campaign_schedules', 'campaign_schedules_option', ['schedules_option_id'], ['id'])
    op.create_foreign_key(None, 'campaign_templates', 'lead_source', ['source_id'], ['id'])
    # ### end Alembic commands ###
    t_campaign_schedules_option = sa.Table(
        'campaign_schedules_option',
        sa.MetaData(),
        sa.Column('type', sa.String()), 
        sa.Column('numeric_value', sa.Integer()), 
        sa.Column('temporal_value', sa.String()), 
        ) 
   
    clients3 = [{'type': 'ONCE', 'numeric_value': 0, 'temporal_value': 'SECONDS'},
{'type': 'ONCE', 'numeric_value': 15, 'temporal_value': 'MINUTES'},
{'type': 'ONCE', 'numeric_value': 30, 'temporal_value': 'MINUTES'},
{'type': 'ONCE', 'numeric_value': 1, 'temporal_value': 'HOURS'},
{'type': 'ONCE', 'numeric_value': 3, 'temporal_value': 'HOURS'},
{'type': 'ONCE', 'numeric_value': 1, 'temporal_value': 'DAYS'},
{'type': 'ONCE', 'numeric_value': 3, 'temporal_value': 'DAYS'},
{'type': 'REPEAT', 'numeric_value': 15, 'temporal_value': 'DAYS'},
{'type': 'REPEAT', 'numeric_value': 1, 'temporal_value': 'WEEKS'}]
    
    op.bulk_insert(t_campaign_schedules_option, clients3)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaign_templates', type_='foreignkey')
    op.drop_constraint(None, 'campaign_schedules', type_='foreignkey')
    op.drop_column('campaign_schedules', 'schedules_option_id')
    op.drop_table('campaign_schedules_option')
    # ### end Alembic commands ###
