"""Added message read or not not field into message table

Revision ID: 3582f75bcf06
Revises: 17091df7d72b
Create Date: 2021-10-11 13:48:50.495756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3582f75bcf06'
down_revision = '17091df7d72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_read', sa.Boolean(), nullable=True))

    op.execute('UPDATE message SET is_read = True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_read')
    # ### end Alembic commands ###
