"""Added is source field for differentiate the source type

Revision ID: 1eee6416b4af
Revises: c5524ad145e8
Create Date: 2021-09-10 12:41:55.385039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eee6416b4af'
down_revision = 'c5524ad145e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_source', sa.Column('is_source', sa.Boolean(), nullable=True))
    op.execute('UPDATE lead_source SET is_source = True')
    op.execute("INSERT INTO lead_source (name, is_source) VALUES ('Unknown', False)")
    op.execute("INSERT INTO lead_source (name, is_source) VALUES ('Phone Up', False)")
    op.execute("INSERT INTO lead_source (name, is_source) VALUES ('Fresh UP', False)")
    op.execute("UPDATE leads SET lead_source_original_id = (SELECT id FROM lead_source WHERE name = 'Unknown' LIMIT 1) WHERE lead_source_original_id is null")
    # ### end Alembic commands ###


def downgrade():
    op.execute("UPDATE leads SET lead_source_original_id = null WHERE lead_source_original_id = (SELECT id FROM lead_source WHERE name = 'Unknown' LIMIT 1)")
    op.execute("DELETE FROM lead_source WHERE name = 'Unknown'")
    op.execute("DELETE FROM lead_source WHERE name = 'Phone Up'")
    op.execute("DELETE FROM lead_source WHERE name = 'Fresh UP'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_source', 'is_source')
    # ### end Alembic commands ###

