"""Created Appointment History

Revision ID: 95b6591035e6
Revises: e8fffc7de443
Create Date: 2021-09-08 12:22:59.178242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95b6591035e6'
down_revision = 'e8fffc7de443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('lead_email', sa.String(), nullable=True),
    sa.Column('lead_phone', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('appointment_status', sa.Enum('SCHEDULED', 'RESCHEDULED', 'CANCELLED', name='appointmentstatus'), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    message_type = postgresql.ENUM('APPOINTMENT', 'REMINDER', 'NORMAL', name='messagetype')
    message_type.create(op.get_bind())

    op.add_column('appointment', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('appointment', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('message', sa.Column('message_type', sa.Enum('APPOINTMENT', 'REMINDER', 'NORMAL', name='messagetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message_type')
    op.drop_column('appointment', 'timezone')
    op.drop_column('appointment', 'date_created')
    op.drop_table('appointment_history')
    # ### end Alembic commands ###
    op.execute("DROP TYPE messagetype;")
    op.execute("DROP TYPE appointmentstatus;")
