"""Added lead_created_date in leads table

Revision ID: 165d2fb1f4b8
Revises: f52ffb9cf50e
Create Date: 2021-07-30 11:57:47.183029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165d2fb1f4b8'
down_revision = 'f52ffb9cf50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lead_created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'lead_created_date')
    # ### end Alembic commands ###
