"""Added STATUS type in campaign type enum

Revision ID: 75c04620fd88
Revises: 20766a423ec2
Create Date: 2021-10-06 13:32:35.733379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c04620fd88'
down_revision = '20766a423ec2'
branch_labels = None
depends_on = None

### Defined enum type and temp type for add & remove field value.
name = 'campaigntype'
tmp_name = 'tmp_' + name

old_options = ('DEFAULT', 'SOURCE', 'LEAD', 'FILE')
new_options = ('DEFAULT', 'SOURCE', 'LEAD', 'FILE', 'STATUS')

old_type = sa.Enum(*old_options, name = name)
new_type = sa.Enum(*new_options, name = name)

tcr = sa.sql.table('campaign_selections', sa.Column('type', new_type, nullable=False))

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lead_status_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'lead_status_type', ['lead_status_type_id'], ['id'])
    # ### end Alembic commands ###

    op.execute('''
                    UPDATE leads SET lead_status_type_id = a.lead_status_type_id
                        FROM
                            (
                                SELECT lead_id, lead_status_type_id 
                                    FROM lead_status_history 
                                    WHERE is_active = true
                            ) 
                            as a
                        WHERE id = a.lead_id
                ''')

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    new_type.create(op.get_bind())
    op.execute('ALTER TABLE campaign_selections ALTER COLUMN type ' +
               'TYPE ' + name + ' USING type::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leads_lead_status_type_id_fkey', 'leads', type_='foreignkey')
    op.drop_column('leads', 'lead_status_type_id')
    # ### end Alembic commands ###

    op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

    old_type.create(op.get_bind())
    op.execute('ALTER TABLE campaign_selections ALTER COLUMN type ' +
               'TYPE ' + name + ' USING type::text::' + name)
    op.execute('DROP TYPE ' + tmp_name)
