"""Added message_sid and message_status

Revision ID: f52ffb9cf50e
Revises: 036a633d1b66
Create Date: 2021-07-26 11:16:29.740162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52ffb9cf50e'
down_revision = '036a633d1b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_sid', sa.String(), nullable=True))
    op.add_column('message', sa.Column('message_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message_status')
    op.drop_column('message', 'message_sid')
    # ### end Alembic commands ###
