"""added on cascade delete on campaign id


Revision ID: db84d2599d6d
Revises: f2d15988a02e
Create Date: 2021-09-23 16:03:12.093351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db84d2599d6d'
down_revision = 'f2d15988a02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campaign_lead_summary_campaign_id_fkey', 'campaign_lead_summary', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_lead_summary', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('campaign_schedules_campaign_id_fkey', 'campaign_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_schedules', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('campaign_selections_campaign_id_fkey', 'campaign_selections', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_selections', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('campaign_templates_campaign_id_fkey', 'campaign_templates', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_templates', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campaign_templates_campaign_id_fkey', 'campaign_templates', type_='foreignkey')
    op.create_foreign_key('campaign_templates_campaign_id_fkey', 'campaign_templates', 'campaign', ['campaign_id'], ['id'])
    op.drop_constraint('campaign_selections_campaign_id_fkey', 'campaign_selections', type_='foreignkey')
    op.create_foreign_key('campaign_selections_campaign_id_fkey', 'campaign_selections', 'campaign', ['campaign_id'], ['id'])
    op.drop_constraint('campaign_schedules_campaign_id_fkey', 'campaign_schedules', type_='foreignkey')
    op.create_foreign_key('campaign_schedules_campaign_id_fkey', 'campaign_schedules', 'campaign', ['campaign_id'], ['id'])
    op.drop_constraint("campaign_lead_summary_campaign_id_fkey", 'campaign_lead_summary', type_='foreignkey')
    op.create_foreign_key('campaign_lead_summary_campaign_id_fkey', 'campaign_lead_summary', 'campaign', ['campaign_id'], ['id'])
    # ### end Alembic commands ###
