"""Added accept_terms and timestamp and delete fields in campaign table

Revision ID: 036a633d1b66
Revises: 6de0d0ada5a0
Create Date: 2021-07-21 10:01:44.592720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036a633d1b66'
down_revision = '6de0d0ada5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('is_accept_terms', sa.Boolean(), nullable=True))
    op.add_column('campaign', sa.Column('accept_terms_timestamp', sa.DateTime(), nullable=True))
    #op.add_column('campaign', sa.Column('is_disabled', sa.Boolean(), nullable=True, default=True))
    op.drop_column('campaign_schedules', 'numeric_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_schedules', sa.Column('numeric_value', sa.INTEGER(), autoincrement=False, nullable=True))
    #op.drop_column('campaign', 'is_disabled')
    op.drop_column('campaign', 'accept_terms_timestamp')
    op.drop_column('campaign', 'is_accept_terms')
    # ### end Alembic commands ###
