"""Added automatic_engagement field in company

Revision ID: b0e521d78396
Revises: c61b51e8c002
Create Date: 2021-07-18 20:47:07.019903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0e521d78396'
down_revision = 'c61b51e8c002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_schedules', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('campaign_schedules', 'schedules_option_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('campaign_schedules', 'temporal_value')
    op.drop_column('campaign_schedules', 'type')
    #op.drop_column('campaign_schedules', 'numeric_value')
    op.add_column('company', sa.Column('automatic_engagement', sa.Boolean(), default=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'automatic_engagement')
    op.add_column('campaign_schedules', sa.Column('type', postgresql.ENUM('ONCE', 'REPEAT', name='scheduletype'), autoincrement=False, nullable=True))
    op.add_column('campaign_schedules', sa.Column('temporal_value', postgresql.ENUM('SECOUNDS', 'MINUTES', 'HOURS', 'DAYS', 'WEEKS', 'MONTHS', 'SECONDS', name='temporaltype'), autoincrement=False, nullable=True))
    op.alter_column('campaign_schedules', 'schedules_option_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('campaign_schedules', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
