# Generated by Django 3.2.5 on 2021-11-10 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('status', models.BooleanField()),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('horizontal_distance', models.PositiveIntegerField(default=0)),
                ('vertical_distance', models.PositiveIntegerField(default=0)),
                ('horizontal_position', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], max_length=255)),
                ('vertical_position', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
