"""
Django settings for AR project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import stripe
from pathlib import Path


from rest_framework import permissions
from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f_t4o9(p7fl&l45yb(zne#gf3l#jy=mh7#o5&^k%ybw$=8swmu'

# SECURITY WARNING: don't run with debug turned on in production!
DEVELOPMENT = True
DEBUG = True


ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ar_builder',
    'user',
    'tradies',
    'company',
    'project',
    'layer',
    'stage',
    'settings',
    'payment',
    'rest_framework',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AR.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR / "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AR.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if DEVELOPMENT:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'ar',
            'USER': 'postgres',
            'PASSWORD': 'root',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'ARConveyancerWeb',
            'USER': 'postgres',
            'PASSWORD': 'StrongAdminP@ssw0rd',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'UTC' #'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [str(BASE_DIR / "static")]
STATIC_ROOT = str(BASE_DIR / "staticfiles")

MEDIA_ROOT = str(BASE_DIR / "media")
MEDIA_URL = "/media/"
MEDIA_FILE_PATH = '{file_type}/{timestamp}/{file_name}'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

from django.urls import reverse_lazy as _
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'user.User'
LOGIN_REDIRECT_URL = _('dashboard')
LOGOUT_REDIRECT_URL = _('login')
LOGIN_URL = _('login')


# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_PORT = 587
EMAIL_HOST_USER = '2excel.testemail@gmail.com'
EMAIL_HOST_PASSWORD = '2excel123'
DEFAULT_FROM_EMAIL = 'suppor<2excel.testemail@gmail.com>'


from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR : 'danger'
}


ENCRYPT_KEY = b'hkv-DWFEMo76xLGrcQW9Cpv8JBINL7C9lFvgqzF0zwQ='


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'AR.permissions.IsAPIUser',
    ]
}


# API ADMIN CREDENTIALS
API_ADMIN_EMAIL = 'apiadmin@admin.com'
API_ADMIN_PASSWORD = 'AR@api-com.1'


# STRIPE
STRIPE_PUBLIC_KEY = "pk_test_51JN9rLSELLTVTa8qg7HLf8bB6QcY4Xi6zuDciLRXZtSU85yYLzpkrH930f5LFitZrSkrZXeBpbTHQ5d9J9d2ZjnR00ZJ64Sibb" 
STRIPE_PRIVATE_KEY = "sk_test_51JN9rLSELLTVTa8q8cNF9pZn0xHZD9zmeFolwkFPEAREBul3GdtPdPmsUNzY0JTtVxVJOIVFWaeQmYBiVf2xQMqr00HN4aq9RD"
stripe.api_key = "sk_test_51JN9rLSELLTVTa8q8cNF9pZn0xHZD9zmeFolwkFPEAREBul3GdtPdPmsUNzY0JTtVxVJOIVFWaeQmYBiVf2xQMqr00HN4aq9RD"



# Django Q
Q_CLUSTER = {
    'name': 'AR',
    'workers': 1,
    'recycle': 500,
    'timeout': 60,
    'cpu_affinity': 1,
    'label': 'Django Q',
    'orm': 'default',
}


DJANGO_Q_TASKS = [
    'user.tasks.end_free_trial',
    'user.tasks.payment',
]
